name: Backend API Tests CI

on:
  pull_request:
    branches: [ "main", "dev", "staging"]

jobs:
  test:
    name: test-api
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Instalar dependencias
      run: npm ci

    - name: Generar Prisma Client
      run: npx prisma generate

    - name: test-api
      run: npm test